---
- name: Ansible playbook to deploy YOLO app using prebuilt DockerHub images
  hosts: all
  become: true
  roles: 
    - docker-setup 
    - frontend-deployment 
    - mongo-deployment
    - backend-deployment
    
    