- name: Ensure Docker network exists
  docker_network:
    name: app-net
    state: present

- name: Pull YOLO frontend image
  docker_image:
    name: virgotex/yolo-client
    tag: v1.0.1
    source: pull

- name: Run frontend container
  docker_container:
      - name: app-net
    name: yolo-client
    image: virgotex/yolo-client:v1.0.1
    restart_policy: unless-stopped
    ports:
      - "3000:80"
    networks: