---
- name: Pull Yolo Backend Docker Image
  docker_image:
    name: virgotex/yolo-backend:v1.0.0
    source: pull

- name: Run Yolo Backend Container
  docker_container:
    name: yolo-backend
    image: virgotex/yolo-backend:v1.0.0
    restart_policy: unless-stopped
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
    env:
      MongoDB_URI: "mongodb://app-mongo:27017/yolo"
  become: yes
  